# Generated by Django 4.2.24 on 2025-09-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('blood_group', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50)),
                ('work_location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('joining_date', models.DateField()),
                ('probation_end_date', models.DateField()),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('resignation_date', models.DateField(blank=True, null=True)),
                ('last_working_day', models.DateField(blank=True, null=True)),
                ('on_probation', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('last_salary_slip', models.FileField(blank=True, null=True, upload_to='employee_docs/salary_slips/')),
                ('academic_certificate', models.FileField(blank=True, null=True, upload_to='employee_docs/certificates/')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='employee_docs/aadhar/')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='employee_docs/profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
